# 201568425 204687842
# cahanaa1 engelbo

compile: bin
	javac -cp src -d bin src/*.java
run:
	java -cp bin ExpressionsTest
bonus:
	java -cp bin SimplificationDemo
check:
	java -jar checkstyle-5.7-all.jar -c biuoop.xml src/*.java
bin:
	mkdir bin