# 201568425 204687842
# cahanaa1 engelbo
compile: bin
	javac -cp src -d bin src/Factorial.java src/DescribeNumbers.java src/Sort.java
run1:
	java -cp bin Factorial 5
run2:
	java -cp bin DescribeNumbers 1 3 5 0 9
run3:
	java -cp bin Sort asc 62 10 0 -8 7
	java -cp bin Sort desc 62 10 0 -8 7
bin:
	mkdir bin